apiVersion: apps/v1
kind: Deployment
metadata:
  name: technotim-docs
spec:
  selector:
    matchLabels:
      app: technotim-docs
  replicas: 2
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: technotim-docs
      annotations:
        deploy-date: "deploy-date-value"
    spec:
      containers:
      - name: technotim-docs
        image: "registry-value:latest"
        ports: 
        - containerPort: 80
      imagePullSecrets: 
      - name: registry-credentials-gitlab
